<?php
/**
 * Created by PhpStorm.
 * User: jaskokoyn
 * Date: 3/7/2015
 * Time: 6:25 PM
 */

$countryArray = array(
    array('code' => 'AE', 'country' => 'United Arab Emirates' ), array('code' => 'AF', 'country' => 'Afghanistan' ),
    array('code' => 'AG', 'country' => 'Antigua and Barbuda' ), array('code' => 'AL', 'country' => 'Albania' ),
    array('code' => 'AM', 'country' => 'Armenia' ), array('code' => 'AO', 'country' => 'Angola' ),
    array('code' => 'AR', 'country' => 'Argentia' ), array('code' => 'AT', 'country' => 'Austria' ),
    array('code' => 'AU', 'country' => 'Australia' ), array('code' => 'AZ', 'country' => 'Azerbaijan' ),
    array('code' => 'BA', 'country' => 'Bosnia and Herzegovina' ), array('code' => 'BB', 'country' => 'Barbados' ),
    array('code' => 'BD', 'country' => 'Bangladesh' ), array('code' => 'BE', 'country' => 'Belgium' ),
    array('code' => 'BF', 'country' => 'Burkina Faso' ), array('code' => 'BG', 'country' => 'Bulgaria' ),
    array('code' => 'BI', 'country' => 'Burundi' ), array('code' => 'BJ', 'country' => 'Benin' ),
    array('code' => 'BN', 'country' => 'Brunei Darussalam' ), array('code' => 'BO', 'country' => 'Bolivia' ),
    array('code' => 'BR', 'country' => 'Brazil' ), array('code' => 'BS', 'country' => 'Bahamas' ),
    array('code' => 'BT', 'country' => 'Bhutan' ), array('code' => 'BW', 'country' => 'Botswana' ),
    array('code' => 'BY', 'country' => 'Belarus' ), array('code' => 'BZ', 'country' => 'Belize' ),
    array('code' => 'CA', 'country' => 'Canada' ), array('code' => 'CF', 'country' => 'Central African Republic' ),
    array('code' => 'CG', 'country' => 'Congo' ), array('code' => 'CH', 'country' => 'Switzerland' ),
    array('code' => 'CI', 'country' =>  "Cote d'Ivoire" ), array('code' => 'CL', 'country' => 'Chile' ),
    array('code' => 'CM', 'country' => 'Cameroon' ), array('code' => 'CN', 'country' => 'China' ),
    array('code' => 'CO', 'country' => 'Colombia' ), array('code' => 'CR', 'country' => 'Costa Rica' ),
    array('code' => 'CU', 'country' => 'Cuba' ), array('code' => 'CV', 'country' => 'Cape Verde' ),
    array('code' => 'CY', 'country' => 'Cyprus' ), array('code' => 'CZ', 'country' => 'Czech Republic' ),
    array('code' => 'DE', 'country' => 'Germany' ), array('code' => 'DJ', 'country' => 'Djibouti' ),
    array('code' => 'DK', 'country' => 'Denmark' ), array('code' => 'DM', 'country' => 'Dominica' ),
    array('code' => 'DO', 'country' => 'Dominican Republic' ), array('code' => 'DZ', 'country' => 'Algeria' ),
    array('code' => 'EC', 'country' => 'Ecuador' ), array('code' => 'EE', 'country' => 'Estonia' ),
    array('code' => 'EG', 'country' => 'Egypt' ), array('code' => 'ER', 'country' => 'Eritrea' ),
    array('code' => 'ES', 'country' => 'Spain' ), array('code' => 'ET', 'country' => 'Ethiopia' ),
    array('code' => 'FI', 'country' => 'Finland' ), array('code' => 'FJ', 'country' => 'Fiji' ),
    array('code' => 'FK', 'country' => 'Falkland Islands' ), array('code' => 'FR', 'country' => 'France' ),
    array('code' => 'GA', 'country' => 'Gabon' ), array('code' => 'GB', 'country' => 'United Kingdom' ),
    array('code' => 'GD', 'country' => 'Grenada' ), array('code' => 'GE', 'country' => 'Georgia' ),
    array('code' => 'GF', 'country' => 'French Guiana' ), array('code' => 'GH', 'country' => 'Ghana' ),
    array('code' => 'GL', 'country' => 'Greenland' ), array('code' => 'GM', 'country' => 'Gambia' ),
    array('code' => 'GN', 'country' => 'Guinea' ), array('code' => 'GQ', 'country' => 'Equatorial Guinea' ),
    array('code' => 'GR', 'country' => 'Greece' ), array('code' => 'GT', 'country' => 'Guatemala' ),
    array('code' => 'GW', 'country' => 'Guinea-Bissau' ), array('code' => 'GY', 'country' => 'Guyana' ),
    array('code' => 'HN', 'country' => 'Honduras' ), array('code' => 'HR', 'country' => 'Croatia' ),
    array('code' => 'HT', 'country' => 'Haiti' ), array('code' => 'HU', 'country' => 'Hungary' ),
    array('code' => 'ID', 'country' => 'Indonesia' ), array('code' => 'IE', 'country' => 'Ireland' ),
    array('code' => 'IL', 'country' => 'Israel' ), array('code' => 'IN', 'country' => 'India' ),
    array('code' => 'IQ', 'country' => 'Iraq' ), array('code' => 'IR', 'country' => 'Iran' ),
    array('code' => 'IS', 'country' => 'Iceland' ), array('code' => 'IT', 'country' => 'Italy' ),
    array('code' => 'JM', 'country' => 'Jamaica' ), array('code' => 'JO', 'country' => 'Jordan' ),
    array('code' => 'JP', 'country' => 'Japan' ), array('code' => 'KE', 'country' => 'Kenya' ),
    array('code' => 'KG', 'country' => 'Kyrgyz Republic' ), array('code' => 'KH', 'country' => 'Cambodia' ),
    array('code' => 'KM', 'country' => 'Comoros' ), array('code' => 'KN', 'country' => 'Saint Kitts and Nevis' ),
    array('code' => 'KP', 'country' => 'North Korea' ), array('code' => 'KR', 'country' => 'South Korea' ),
    array('code' => 'KW', 'country' => 'Kuwait' ), array('code' => 'KZ', 'country' => 'Kazakhstan' ),
    array('code' => 'LA', 'country' => "Lao People's Democratic Republic" ), array('code' => 'LB', 'country' => 'Lebanon' ),
    array('code' => 'LC', 'country' => 'Saint Lucia' ), array('code' => 'LK', 'country' => 'Sri Lanka' ),
    array('code' => 'LR', 'country' => 'Liberia' ), array('code' => 'LS', 'country' => 'Lesotho' ),
    array('code' => 'LT', 'country' => 'Lithuania' ), array('code' => 'LV', 'country' => 'Latvia' ),
    array('code' => 'LY', 'country' => 'Libya' ), array('code' => 'MA', 'country' => 'Morocco' ),
    array('code' => 'MD', 'country' => 'Moldova' ), array('code' => 'MG', 'country' => 'Madagascar' ),
    array('code' => 'MK', 'country' => 'Macedonia' ), array('code' => 'ML', 'country' => 'Mali' ),
    array('code' => 'MM', 'country' => 'Myanmar' ), array('code' => 'MN', 'country' => 'Mongolia' ),
    array('code' => 'MR', 'country' => 'Mauritania' ), array('code' => 'MT', 'country' => 'Malta' ),
    array('code' => 'MU', 'country' => 'Mauritius' ), array('code' => 'MV', 'country' => 'Maldives' ),
    array('code' => 'MW', 'country' => 'Malawi' ), array('code' => 'MX', 'country' => 'Mexico' ),
    array('code' => 'MY', 'country' => 'Malaysia' ), array('code' => 'MZ', 'country' => 'Mozambique' ),
    array('code' => 'NA', 'country' => 'Namibia' ), array('code' => 'NC', 'country' => 'New Caledonia' ),
    array('code' => 'NE', 'country' => 'Niger' ), array('code' => 'NG', 'country' => 'Nigeria' ),
    array('code' => 'NI', 'country' => 'Nicaragua' ), array('code' => 'NL', 'country' => 'Netherlands' ),
    array('code' => 'NO', 'country' => 'Norway' ), array('code' => 'NP', 'country' => 'Nepal' ),
    array('code' => 'NZ', 'country' => 'New Zealand' ), array('code' => 'OM', 'country' => 'Oman' ),
    array('code' => 'PA', 'country' => 'Panama' ), array('code' => 'PE', 'country' => 'Peru' ),
    array('code' => 'PF', 'country' => 'French Polynesia' ), array('code' => 'PG', 'country' => 'Papua New Guinea' ),
    array('code' => 'PH', 'country' => 'Philippines' ), array('code' => 'PK', 'country' => 'Pakistan' ),
    array('code' => 'PL', 'country' => 'Poland' ), array('code' => 'PT', 'country' => 'Portugal' ),
    array('code' => 'PY', 'country' => 'Paraguay' ), array('code' => 'QA', 'country' => 'Qatar' ),
    array('code' => 'RE', 'country' => 'Reunion' ), array('code' => 'RO', 'country' => 'Romania' ),
    array('code' => 'RS', 'country' => 'Serbia' ), array('code' => 'RU', 'country' => 'Russian Federation' ),
    array('code' => 'RW', 'country' => 'Rwanda' ), array('code' => 'SA', 'country' => 'Saudi Arabia' ),
    array('code' => 'SB', 'country' => 'Solomon Islands' ), array('code' => 'SC', 'country' => 'Seychelles' ),
    array('code' => 'SD', 'country' => 'Sudan' ), array('code' => 'SE', 'country' => 'Sweden' ),
    array('code' => 'SI', 'country' => 'Slovenia' ), array('code' => 'SK', 'country' => 'Slovakia' ),
    array('code' => 'SL', 'country' => 'Sierra Leone' ), array('code' => 'SN', 'country' => 'Senegal' ),
    array('code' => 'SO', 'country' => 'Somalia' ), array('code' => 'SR', 'country' => 'Suriname' ),
    array('code' => 'ST', 'country' => 'Sao Tome and Principe' ), array('code' => 'SV', 'country' => 'El Salvador' ),
    array('code' => 'SY', 'country' => 'Syrian Arab Republic' ), array('code' => 'SZ', 'country' => 'Swaziland' ),
    array('code' => 'TD', 'country' => 'Chad' ), array('code' => 'TG', 'country' => 'Togo' ),
    array('code' => 'TH', 'country' => 'Thailand' ), array('code' => 'TJ', 'country' => 'Tajikistan' ),
    array('code' => 'TL', 'country' => 'Timor-Leste' ), array('code' => 'TM', 'country' => 'Turkmenistan' ),
    array('code' => 'TN', 'country' => 'Tunisia' ), array('code' => 'TR', 'country' => 'Turkey' ),
    array('code' => 'TT', 'country' => 'Trinidad and Tobago' ), array('code' => 'TW', 'country' => 'Taiwan' ),
    array('code' => 'TZ', 'country' => 'Tanzania' ), array('code' => 'UA', 'country' => 'Ukraine' ),
    array('code' => 'UG', 'country' => 'Uganda' ), array('code' => 'US', 'country' => 'United States of America' ),
    array('code' => 'UY', 'country' => 'Uruguay' ), array('code' => 'UZ', 'country' => 'Uzbekistan' ),
    array('code' => 'VE', 'country' => 'Venezuela' ), array('code' => 'VN', 'country' => 'Vietnam' ),
    array('code' => 'VU', 'country' => 'Vanuatu' ), array('code' => 'YE', 'country' => 'Yemen' ),
    array('code' => 'ZA', 'country' => 'South Africa' ), array('code' => 'ZM', 'country' => 'Zambia' ),
    array('code' => 'ZW', 'country' => 'Zimbabwe' )
);